### ISSUE TITLE
Migrating SequenceNr from < 1.1.0-3-beta

### ISSUE THREAD

**Issue by jackowild** [AkkaNetContrib/Akka.Persistence.MongoDB#24]
I recently upgraded 1.0.5.2-beta to 1.1.0.3-beta and attempted to run my actor system which already had events persisted from 1.0.5.2-beta. Upon persisting an event I was greeted with the following error:

```
2017-01-26 12:44:25.016 +00:00 [Warning] Rejected to persist event type ["SomeEvent"] with sequence number [1] for persistenceId ["EventPollActor"] due to ["A bulk write operation resulted in one or more errors.
  E11000 duplicate key error collection: loans.EventJournal index: _id_ dup key: { : \"EventPollActor_1\" }"].
```

When the actor system tried to persist this event it couldn't because the sequence number it uses to create the _id field already existed in the EventJournal collection.

This is because the SequenceNr has moved to a new Metadata table instead of EventJournal.

Looking at Akka.Persistence.SqlServer and Akka.Persistence.PostgreSql, they have migration scripts for this problem whereby the sequence number is moved from EventJournal to Metadata. I was wondering if anyone has written one already for mongodb? I'm happy to write one myself and contribute however my Mongo skills aren't the best.

**Comment by Danthar** [comment]
I don't think any has written one so far. Any contributions on this end would be very appreciated.
