### ISSUE TITLE
Add support for cluster sharding persistence

### ISSUE THREAD

**Issue by enashed** [AkkaNetContrib/Akka.Persistence.MongoDB#26]
Are there any plans to update this plugin to support cluster sharding persistence?

Currently if you use Akka.Persistence.MongoDB as a persistence plugin for cluster sharding, it fails to serialize messages. Even if you register the types using RegisterClassMap. You end up with an empty payload like this:

    "Payload" : {
        "_t" : "ShardRegionRegistered"
    }, 

In sql plugin, it uses binary serialisation to generate byte[], so hyperion serializer works fine with all those payloads. But in mongo, when BsonSerializer comes accross those messages: 
ex: ShardRegionRegistered, ShardHomeAllocated, ShardHomeDeallocated, etc. It always generates an empty payload.

**Comment by Aaronontheweb** [comment]
closed via #42
