### ISSUE TITLE
New version of Akka.Persistence.MongoDB

### ISSUE THREAD

**Issue by waelemara** [AkkaNetContrib/Akka.Persistence.MongoDB#35]
Hi,
The last version of Akka.Persistence.MongoDB is 1.1.0.3-beta, released on August 2nd, 2016
I was wondering if you can release a new version, there are some PRs that have been merged, and I see new code updates in the last month.

![image](https://user-images.githubusercontent.com/4891878/37168470-18163f68-2359-11e8-8f26-224fadb74e90.png)

Thanks

**Comment by waelemara** [comment]
Also just found out that the new Persistence Query Apis not available, dotnet core not supported yet, 
Happy to raise a PR for dotnet core tho.

**Comment by jackowild** [comment]
I had my PR #30 merged in a few months ago which included .NET Core support. @Aaronontheweb was going to put this project in to the Akka.NET CI system then release on Nuget. He's a busy man though so I'm guessing this was forgotten about. @Aaronontheweb could we re-plan this?

**Comment by Aaronontheweb** [comment]
Sorry for the delay folks; yep, I dropped the ball here. Going to make a couple of fixes momentarily and get these releases and CI going again.

**Comment by diegolinan** [comment]
@Aaronontheweb Great! So will there be an announcement about this or we'll find out here?

**Comment by Aaronontheweb** [comment]
@diegolinan oh no, I'm literally doing this right now actually.

**Comment by Aaronontheweb** [comment]
Consider this your announcement :p

**Comment by diegolinan** [comment]
@Aaronontheweb Oh, cool! So when will it be available exactly? And @jackowild which features are we exactly expecting to have in the new version?

**Comment by Aaronontheweb** [comment]
https://github.com/AkkaNetContrib/Akka.Persistence.MongoDB/issues/36 - need to do this first since MSBuild 15 / .NET Standard breaks everything in our legacy build scripts. Once that's done, going to re-configure TeamCity to start publishing again.

**Comment by diegolinan** [comment]
@jackowild So apparently @Aaronontheweb has merged the PR. Which updates can we expect from that?

**Comment by jackowild** [comment]
See #30 Not much changed, only .NET Standard support and it was updated to latest Akka and Akka.Persistence at the time which was 1.3.2.

**Comment by Aaronontheweb** [comment]
https://github.com/AkkaNetContrib/Akka.Persistence.MongoDB/releases/tag/v1.3.5 - tagged a new release here for v1.3.5. Should be going live to NuGet shortly, provided that I didn't screw up that part of the build system. I'll let you know.

**Comment by Aaronontheweb** [comment]
https://www.nuget.org/packages/Akka.Persistence.MongoDb/1.3.5 - mission accomplished.
