### ISSUE TITLE
Could not connect with MongoDB

### ISSUE THREAD

**Issue by Isuama** [AkkaNetContrib/Akka.Persistence.MongoDB#44]
This is my first MongoDB and Akka persistent setup with console app and .NET Core. I have successfully persisted state on local machine and experienced empty reference when connecting to the MongoDB. I am not sure whether I have done this in a correct way. I am running MongoDB as a Docker and created db name "test" with no collections at all. When I run the application, I do see my connectionstring property in JournalSettings is always set to ""(blank) in my "res" object.  

System = ActorSystem.Create("Service");
var res = MongoDbPersistence.Get(System);

<akka>
  <hocon>
    <![CDATA[
  
    akka {
      loglevel = INFO
      }
      
      akka.persistence {
          journal {
          plugin = "akka.persistence.journal.mongodb"
	          mongodb {
		          # qualified type name of the MongoDb persistence journal actor
		          class = "Akka.Persistence.MongoDb.Journal.MongoDbJournal, Akka.Persistence.MongoDb"

		          # connection string used for database access
		          connection-string = "mongodb://127.0.0.1:27017/test"

		          # should corresponding journal table's indexes be initialized automatically
		          auto-initialize = on

		          # dispatcher used to drive journal actor
		          plugin-dispatcher = "akka.actor.default-dispatcher"

		          # MongoDb collection corresponding with persistent journal
		          collection = "EventJournal"

		          # metadata collection
		          metadata-collection = "Metadata"
	          }
          }         
      }
    }      
  
  ]]>
  </hocon>
</akka>

Is there anything wrong or have I missed out anything?

**Comment by jackowild** [comment]
Where have you defined your hocon? You can't use app.config in .net core, it has to be passed into your actor system as a string e.g.
```
var akkaConfig = Akka.Configuration.ConfigurationFactory.ParseString(hocon);

System = ActorSystem.Create("TestSystem", akkaConfig);
```

I believe the Akka.net team are working on a way to use appsettings.json but it is not out yet.

**Comment by Isuama** [comment]
yes, you are correct. I am using app.config. Could you please elaborate the way of passing hocon.

**Comment by jackowild** [comment]
See https://github.com/jackowild/AkkaPersistenceMongoDbNetCoreExample

Please close this issue if this works for you.

**Comment by Isuama** [comment]
thanks very much @jackowild

**Comment by Isuama** [comment]
for anyone looking for the final outcome, this works fine

var config = ConfigurationFactory.ParseString(@"
                akka.persistence {
                    journal {
                        plugin = ""akka.persistence.journal.mongodb""
                        mongodb {
                            connection-string = ""mongodb://127.0.0.1:27017/test""
                        }
                    }
                }");

System = ActorSystem.Create("Service", config);
